export const notesActions = {
    CREATE_NOTE: "CREATE_NOTE",
    CREATE_NOTE_SUCCESS: "CREATE_NOTE_SUCCESS",
    CREATE_NOTE_ERROR: "CREATE_NOTE_ERROR",
    DELETE_NOTE: "DELETE_NOTE",
    DELETE_NOTE_SUCCESS: "DELETE_NOTE_SUCCESS",
    DELETE_NOTE_ERROR: "DELETE_NOTE_ERROR",
    EDIT_NOTE: "EDIT_NOTE",
    EDIT_NOTE_SUCCESS: "EDIT_NOTE_SUCCESS",
    EDIT_NOTE_ERROR: "EDIT_NOTE_ERROR",
    GET_ALL: "GET_ALL",
    GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
    GET_ALL_ERROR: "GET_ALL_ERROR",
    GET_ONE: "GET_ONE",
    GET_ONE_SUCCESS: "GET_ONE_SUCCESS",
    GET_ONE_ERROR: "GET_ONE_ERROR",
    CLEAR_CURRENT: "CLEAR_CURRENT"
}